### PR TITLE
Add span reporter

### PR DESCRIPTION
**Pull request by stoiev**

### CODE REVIEW

**Comment by rtfpessoa** [comment]
@ivantopo any plans for releasing this?

**Comment by ivantopo** [comment]
Hey folks! Thanks @stoiev for developing this and @rtfpessoa for reminding me :sweat_smile:. Precisely last night I mentioned I wanted to bring this up to a friendly folk from Datadog to take a look but ended up falling asleep. Now we got the chance!

@tylerbenson do you think maybe you or someone on your team could help us take a look at this?

**Comment by tylerbenson** [comment]
@ivantopo it’s a pretty substantial change, so I don’t think I can give it a thorough review. I’m happy to answer specific questions though.

**Comment by rtfpessoa** [comment]
@ivantopo, any news here? Is it possible to get a snapshot release to test?

**Comment by stoiev** [comment]
@rtfpessoa, this PR with one or two more commits is avaiable at [Bintray](https://bintray.com/beta/#/cobli/maven/kamon-datadog?tab=overview). Hope it helps!

@ivantopo,  I'm glad to help on any clarification about these changes.

**Comment by rtfpessoa** [comment]
@stoiev I am doing some tests with this. Overall seems nice but I have some weird results.
Maybe I am doing something wrong.

For example I am not getting the http requests to my endpoints in the list. I get all this internals.
kamon-datadog-reporter

Any ideas?

**Comment by stoiev** [comment]
@rtfpessoa , we are using it with akka-stream, and we had some issues with span filtering (sometimes we got incomplete traces, sometimes a huge incomprehensible trace with all akka-streams internals)

I've developed a console trace dumper (docker based) that helped us to figure out what was going on. You must run it instead of a datadog-agent (on dev/local environment).

```
$ docker run -p 8126:8126 ivanstoiev/opentracing-dumper
WebServer: You can connect to your server at http://localhost:8126/
####################
Trace alterado: 15090975169980406961
                                  ██████████████████████████
                                  █       akka.actor       █
                                  █         Shard:         █
                                  █  ProcessQueueContents  █
                                  █        0.242424        █
                                  ██████████████████████████
                                    │
                                    │
                                    ∨
                                  ┌────────────────────────┐
                                  │       akka.actor       │
                                  │ DeviceActorSupervisor: │
                                  │  ProcessQueueContents  │
                                  │        0.162763        │
                                  └────────────────────────┘
                                    │
                                    │
                                    ∨
┌───────────────────────────┐     ┌────────────────────────────────────────────────────┐     ┌─────────────────┐
│        akka.actor         │     │                     akka.actor                     │     │   akka.actor    │
│ DeviceTotalDistanceActor: │     │                    DeviceActor:                    │     │ RiskEventActor: │
│          Compute          │     │                ProcessQueueContents                │     │     Compute     │
│         3.559862          │ <── │                      3.935019                      │ ──> │     0.57003     │
└───────────────────────────┘     └────────────────────────────────────────────────────┘     └─────────────────┘
                                    │                              │
                                    │                              │
                                    ∨                              ∨
                                  ┌────────────────────────┐     ┌─────────────────────┐
                                  │       akka.actor       │     │     akka.actor      │
                                  │   BackoffSupervisor:   │     │ DevicePluggedActor: │
                                  │        Compute         │     │       Compute       │
                                  │        0.167262        │     │      2.208635       │
                                  └────────────────────────┘     └─────────────────────┘
                                    │                              │
                                    │                              │
                                    ∨                              ∨
                                  ┌────────────────────────┐     ┌─────────────────────┐
                                  │                        │     │      process-       │
                                  │       akka.actor       │     │       device-       │
                                  │    DevicePathActor:    │     │       plugged       │
                                  │        Compute         │     │ DevicePluggedActor: │
                                  │        2.061841        │     │       Compute       │
                                  │                        │     │      6.484937       │
                                  └────────────────────────┘     └─────────────────────┘
                                    │
                                    │
                                    ∨
┌───────────────────────────┐     ┌────────────────────────┐     ┌─────────────────────┐
│         produce-          │     │        process-        │     │        save-        │
│          device-          │     │        device-         │     │       device-       │
│           path            │     │          path          │     │        path         │
│     DevicePathActor:      │     │    DevicePathActor:    │     │  DevicePathActor:   │
│          Compute          │     │        Compute         │     │       Compute       │
│         0.053728          │ <── │        6.462232        │ ──> │      0.032528       │
└───────────────────────────┘     └────────────────────────┘     └─────────────────────┘
                                    │
                                    │
                                    ∨
                                  ┌────────────────────────┐
                                  │       akka.actor       │
                                  │    DevicePathActor:    │
                                  │  SaveSnapshotSuccess   │
                                  │        0.334739        │
                                  └────────────────────────┘
####################
```

**Comment by rtfpessoa** [comment]
@stoiev sent a followup email to avoid too much noise in here. We can then post just the findings.

**Comment by rtfpessoa** [comment]
From my latest tests the reports to Datadog are the same as the ones to Kamon APM.
@ivantopo do you have anything else to test here?

**Comment by ivantopo** [comment]
Hey peoplez! I just published version `1.0.1-575eaa723d43aac28c590289ee55d2279085619b` on our snapshots repository. It contains the changes from this PR, merged with another minor change from #25. It would be great if you can give it a try and if all is fine I will release it as 1.1.0. 

Special thanks to @stoiev for making this effort and @rtfpessoa for all the testing :smile: :tada:

**Pull request merged**
