### PR TITLE
+ datadog: add global-tags

### PR DESCRIPTION
**Pull request by j-martin**
The idea is to allow the application to have global tags to be sent to
datadog. See reference.conf for more explanation.

### CODE REVIEW

**Comment by jgagnon1** [comment]
+1 on this; this would be really helpful for some of the use case I have. @dpsoft can you take a look at this PR ?

**Comment by dpsoft** [comment]
@j-martin  thanks for proposing this PR, please sign our [CLA](https://docs.google.com/forms/d/1G_IDrBTFzOMwHvhxfKRBwNtpRelSa_MZ6jecH8lpTlc/viewform)  we are good to go!

**Comment by j-martin** [comment]
I signed it, just now. Cheers.

**Comment by dpsoft** [comment]
@j-martin thanks for proposing this PR!!

**Pull request merged**
