### PR TITLE
Add ability to report metrics directy to datadog using the API

### PR DESCRIPTION
**Pull request by jypma**
Not tested yet. PR created to see if the direction is the right one :-)

### CODE REVIEW

**Comment by dpsoft** [comment]
@jypma thanks for proposing this PR!!

**Comment by jypma** [comment]
@dpsoft I didn't notice this PR already had been merged :-) Like I said, the PR was just to check direction, and is not tested... did you actually _run_ the code?

**Comment by dpsoft** [comment]
@jypma sorry for the late response, I've run a mini test ;) but yes, it need more love..

**Comment by jypma** [comment]
Great to hear that :-) We will move on this at some point, as we're getting more and more upset with `dogstatsd` being in the middle. Unsure about timelines though.

**Comment by dpsoft** [comment]
@jypma sure, thanks again!!!

**Pull request merged**
